### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Messi10AP** [rohanp/MessengerGrapher#6]
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    soup = BeautifulSoup(open("messages.htm").read(), 'html.parser')
  File "C:\Users\abhi1\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 273053: character maps to <undefined>

**Comment by rohanp** [comment]
https://github.com/rohanp/MessengerGrapher/commit/7bede4691b270e6578339d94fbc48a5a9236694f solves this
